# Generated by Django 5.2.8 on 2026-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Wearable de Reabilitação', max_length=100)),
                ('descricao', models.TextField(help_text='Breve resumo do projeto')),
                ('tag', models.CharField(help_text='Ex: Engenharia Biomédica', max_length=50)),
                ('data', models.CharField(help_text='Ex: Out 2025', max_length=20)),
                ('tech_1', models.CharField(help_text='Ex: C++', max_length=30)),
                ('tech_2', models.CharField(help_text='Ex: Biomecânica', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
