# Generated by Django 5.2.8 on 2026-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Faça o upload da imagem do projeto', null=True, upload_to='projetos_capas/'),
        ),
    ]
