# Generated by Django 5.2.8 on 2026-03-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projeto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Python, C++, Django, Biomecânica', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tech_1',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tech_2',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos_capas/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(related_name='projetos', to='portfolio.tecnologia'),
        ),
    ]
